apiVersion: v1
kind: Service
metadata:
  name: {{ include "zenbu-roadmaps.name" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "zenbu-roadmaps.name" . }}-api
    {{- include "zenbu-roadmaps.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "zenbu-roadmaps.name" . }}-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
