{{- if .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zenbu-roadmaps.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret }}
{{- end }}
